version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    
    ports:
      - "80:8000"

    
    # volume de mídia persistente porém não espelha a pasta local
    volumes:
      - media_data:/app/media

    env_file:
      - .env

    environment:
      DJANGO_ALLOWED_HOSTS: "seu-dominio.com, www.seu-dominio.com"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DJANGO_SETTINGS_MODULE: config.settings.production

    depends_on:
      db:
        condition: service_healthy
    
    command: poetry run gunicorn --workers=4 --bind=0.0.0.0:8000 config.wsgi:application
  
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: twitter_clone_prod_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  media_data: