# Generated by Django 5.2.1 on 2025-07-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
    ]
